version: "3"

services:
  mongo:
    image: mongo:4.4-bionic
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

  app:
    image: "${COMPOSE_PROJECT_NAME}_app"
    build: .
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - "${APP_EXTERNAL_PORT}:80"
    environment:
      PORT: 80
      NODE_ENV: "docker"
    env_file: .env

volumes:
    mongodb-data:
